import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ['500', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          {/* <Navbar/> */}
          {children}
          <div className="w-full bg-blue-500  h-10 flex justify-center items-center text-white mt-12">
            Ritik Patil 😎 All Rights Reserved
          </div>
      </body>
    </html>
  );
}
