import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ['500', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <link rel="icon" href="/letter-s.png" sizes="any" type="image/png" />
      </Head>
      <body className={poppins.className}>
        {/* <Navbar/> */}
        {children}
        <div className="w-full bg-blue-500  h-10 flex justify-center items-center text-white mt-12">
          Ritik Patil 😎 All Rights Reserved
        </div>
      </body>
    </html>
  );
}
